### ISSUE TITLE
Alternative configuration procedure

### ISSUE THREAD

**Issue by briantopping** [ANierbeck/Karaf-Cassandra#5]
Hi Achim, did you have some considerations for configuring the embedded Cassandra? I've seen the `de.nierbeck.cassandra,embedded` (note comma, should that be a period?) ConfigAdmin key as we discussed, but I'm curious how you've been using it. 

What I'm thinking would be ideal is if the Cassandra client bundle could specify a configuration file located in it's own bundle and configure it through the feature. Since there is a `bundle` URL handler, it would be possible to set the config value to `bundle:...`, but it would have to be generated dynamically since we can't know the bundle ID that was eventually assigned.

Did you have an easier strategy in mind? If not, I'll elaborate on this one more.

**Comment by ANierbeck** [comment]
yeah it actually should be a period ... let me test a bit.
But I had it working, I thought.

2015-09-23 22:13 GMT+02:00 Brian Topping notifications@github.com:

> Hi Achim, did you have some considerations for configuring the embedded
> Cassandra? I've seen the de.nierbeck.cassandra,embedded (note comma,
> should that be a period?) ConfigAdmin key as we discussed, but I'm curious
> how you've been using it.
> 
> What I'm thinking would be ideal is if the Cassandra client bundle could
> specify a configuration file located in it's own bundle and configure it
> through the feature. Since there is a bundle URL handler, it would be
> possible to set the config value to bundle:..., but it would have to be
> generated dynamically since we can't know the bundle ID that was eventually
> assigned.
> 
> Did you have an easier strategy in mind? If not, I'll elaborate on this
> one more.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ANierbeck/Karaf-Cassandra/issues/5.

## 

Apache Member
Apache Karaf http://karaf.apache.org/ Committer & PMC
OPS4J Pax Web http://wiki.ops4j.org/display/paxweb/Pax+Web/ Committer &
Project Lead
blog http://notizblog.nierbeck.de/
Co-Author of Apache Karaf Cookbook http://bit.ly/1ps9rkS

Software Architect / Project Manager / Scrum Master

**Comment by ANierbeck** [comment]
The easier strategy is actually to use a cassandra.yaml file from the etc folder. 
And to prove that it actually works I've added another test for it.

**Comment by briantopping** [comment]
Yes, I was just experimenting with that. I added a `<configfile>` element to my client feature and had it install the configuration file to etc, but having some challenges to get the config installed before the dependency on the `Karaf-Service` fires. https://issues.apache.org/jira/browse/KARAF-2988

Example:

```
    <feature name="${project.artifactId}" version="${project.version}" description="${project.artifactId}">
        <configfile finalname="/etc/com.coglative.mim.domain.cassandra.yaml">mvn:${project.groupId}/${project.artifactId}/${project.version}/config/yaml</configfile>
        <config name="de.nierbeck.cassandra,embedded">
            cassandra.yaml = /etc/com.coglative.mim.domain.cassandra.yaml
        </config>
        <bundle>mvn:${project.groupId}/${project.artifactId}/${project.version}</bundle>
        <feature version="1.0.0-SNAPSHOT" prerequisite="true">Karaf-Cassandra-Embedded</feature>
       ...
    </feature>
```

**Comment by ANierbeck** [comment]
I'm not sure I fully understand your requirement regarding a
"client-feature" one.
The idea is to have an embedded cassandra instance only for running localy
and if you really want to have a configuration with it
in a feature I guess it would look a lot like the one in Pax-Web:

<configfile
finalname="/etc/cassandra.yaml">mvn:de.nierbeck.cassandra/Karaf-Cassandra-Embedded/${project.version}/yaml/cassandra-template</configfile>
<config name="de.nierbeck.cassandra.embedded">
cassandra.yaml=${karaf.base}/etc/cassandra.yaml
</config>

The way configurations work in OSGi will always result in a
re-configuration of the service. And the way the Embedded Cassandra Service
is
configured right now, if there is no such configuration it will start
anyway with the default configuration available inside the jar.
A new configuration will trigger a re-configuration which is intentional.

regards, Achim

2015-09-24 0:00 GMT+02:00 Brian Topping notifications@github.com:

> Yes, I was just experimenting with that. I added a <configfile> element
> to my client feature and had it install the configuration file to etc, but
> having some challenges to get the config installed before the dependency on
> the Karaf-Service fires. https://issues.apache.org/jira/browse/KARAF-2988
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ANierbeck/Karaf-Cassandra/issues/5#issuecomment-142743782
> .

## 

Apache Member
Apache Karaf http://karaf.apache.org/ Committer & PMC
OPS4J Pax Web http://wiki.ops4j.org/display/paxweb/Pax+Web/ Committer &
Project Lead
blog http://notizblog.nierbeck.de/
Co-Author of Apache Karaf Cookbook http://bit.ly/1ps9rkS

Software Architect / Project Manager / Scrum Master

**Comment by briantopping** [comment]
Yep, that worked, thanks. I was missing the `${karaf.base}`, I didn't know that interpolation was possible or what property to use. 

Shall I submit a PR with documentation or is it easier to just add it without one?

**Comment by ANierbeck** [comment]
Documentation is always great fully accepted :-)

sent from mobile device
Am 24.09.2015 1:37 vorm. schrieb "Brian Topping" notifications@github.com:
